### PR TITLE
Intro and data notebooks

### PR DESCRIPTION
**Pull request by petebryan**
Introduction to MSTICPy and Data Acquisition Notebooks

### CODE REVIEW

**Comment by ianhelle** [comment]
IntroToMsticpy
1st exercise - the boilerplate description, 1. step text are still there.
I'm not too comfortable with the "msticpy"= awesome, msticpy is great stuff. :-) 
What about Python or Jupyter is awesome ?
Are you going to tell them that the Image and HTML classes exist 
Typo of Ipyton in hints

**Comment by ianhelle** [comment]
MSTICPys config file. - maybe mention that there is an embryonic file in repo. and that we'll cover config in more depth later.

At which point to do we want them to be running in the right environment? I think we want either:
1. Conda:
    - cmd/terminal with conda environment activated
    - cd to workshops/oct2022
    - run vscode from there
    - have vscode python, jupyter extensions (any others?)
 2. Similar thing but with docker as the vscode backend

**Comment by ianhelle** [comment]
on the init_notebook section. maybe we should describe what this does:
- import stuff
- optionally install packages
- initialize pivot
- initialize AML or Synapse environment (if appropriate)

For the data, visualization, pivots examples - presumably you're going to mention that we have drill downs on all of these items.

**Comment by ianhelle** [comment]
AquiringData
- connect - maybe we should show using a config entry first (since that's a much easier way to use it) but that you can also (for some providers) supply a connection string (actually I think this only works for Kusto and Log analytics right?)
It currently feels like the scary connection string is more like the default route.

Authentication
- I think it would be good start a new section on authentication methods - different providers support different methods (e.g. Splunk has username and password).
- Then talk about the Azure data providers (Sentinel, Kusto, Defender, Graph) and the various auth options.
- Then intro AzureCLI as maybe the least painful way to do cross session cached auth. And that this also works in docker, AML, jupyter hub

**Comment by ianhelle** [comment]
Aquiring Data
before 1st exercise you could also mention using Python help to view query params
and using the qry_prov.schema for viewing tables

**Comment by ianhelle** [comment]
Aquiring data
Kusto
- assuming that we've set up a Kusto connection in the config session, this could be more a reminder/confirmation that we have that config
- Do we want to create/populate some queries for this cluster?

I am noticing a few typos here and there - you might want to spell-check, or maybe export to html and import to word to do a spell/grammar check. (I should prob do that). Do you use a speller extension - I think I use Code Spell check or maybe cspell.

**Comment by ianhelle** [comment]
I think it would be a good idea to show how to create a query - but perhaps in an appendix. I think referring to this in one of the sections (Kusto, Defender) and then showing an example in the appendix of how do this would be great.
I think I have an example in a notebook I did for LearnTV that you might be able to use. https://github.com/ianhelle/pycon2021/blob/main/Extending-MSTICPy.ipynb

**Comment by ianhelle** [comment]
I wonder whether you might be stranding some people in the exercises. Esp if people a pretty new to querying - do you think we can expect people to have good KQL knowledge?

I think it's reasonable to give people a few more hints. Esp since we don't have a lot of time for the exercises, people doing research etc.
E.g. for the resource graph I think you could give the query to use in a hint.
Perhaps we could have multiple hints sections in some of the exercises. 
We should also talk about the existinence of the hints in the intro and perhaps how to use them - e.g. click to open and look at hint 1 then close without looking at further hints and keep going back if they are stuck....something like that.

**Comment by petebryan** [comment]
> I think it would be a good idea to show how to create a query - but perhaps in an appendix. I think referring to this in one of the sections (Kusto, Defender) and then showing an example in the appendix of how do this would be great. I think I have an example in a notebook I did for LearnTV that you might be able to use. https://github.com/ianhelle/pycon2021/blob/main/Extending-MSTICPy.ipynb

I think this is a great idea but I just don't think we have time for it here. Maybe we can add some links to this notebook/documentaiton.

**Comment by ianhelle** [comment]
> I think this is a great idea but I just don't think we have time for it here. Maybe we can add some links to this notebook/documentaiton.
Yeah - I just meant as an appendix, not an actual exercise or something we spend any real time on. I did something like this for creating your own pivot function. Most people won't be creating their own pivot functions or queries but this will be important for some.
I think at least we should mention that you can create your own queries. This isn't obvious unless you dig into the documentation.
Having a short illustration of how to do that as an appendix might help some of the more curious-minded.

I can create an example from the Extending notebook and add it to this notebook if you like.

**Review by ianhelle — APPROVED** [review]

**Comment by petebryan** [comment]
Closing this PR as changes and updated added to #6

**Pull request closed without merging**
